version: "3.1"

volumes:
  pg_selectel:

services:
  pg_db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=Yra
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: "none" # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
